###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "{{package.name}}"
    name: "{{composer.extra.pluginName}}"
    type: plugin
    subtype: wordpress
    version: "{{package.version}}"
    description: "{{composer.description}}"
    homepage: "{{composer.homepage}}"
    repo: "{{composer.repositories.github.url}}"
    logo: "https://raw.githubusercontent.com/{{composer.name}}/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/{{composer.name}}/main/docs/banner.png"


###############################################################################
