###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "fake-admin"
    name: "Fake admin"
    type: 
      - wp-plugin
    version: "{{package.version}}"
    description: "{{composer.description}}"
    homepage: "{{composer.homepage}}"
    repo: "{{composer.repositories.github.url}}"
    logo: "https://raw.githubusercontent.com/{{package.name}}/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/{{package.name}}/main/docs/banner.png"


###############################################################################
