################ PIGEONPOSSE [FAKE ADMIN] - DOCKER-COMPOSE DEV ################
#
# PIGEONPOSSE [FAKE ADMIN]
# 
# @description Run WP enviroment for plugin development.
#              Easy to use.
# @usage       - docker-compose -f docker-compose-dev.yml up -d
#              - pnpm docker-compose-dev
# @link        https://docs.docker.com/compose/
# @link        https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/
#
###############################################################################

version: "3.8"


###############################################################################
# SERVICES
###############################################################################

services:          


  #########################################################################
  # DATABASE
  #########################################################################
  
  db:

    image: mariadb
    container_name: fake-admin-db
    command: --default-authentication-plugin=mysql_native_password  
    volumes:
      - './dev-env/db:/var/lib/mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress


  #########################################################################
  # WP
  #########################################################################
  
  wp:

    image: wordpress:latest
    container_name: fake-admin-wp
    depends_on:
      - db
    ports:
      - 41312:80
    restart: always
    volumes:
      - ./dev-env/wp:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/fake-admin
      - ./dev-env/wp-cli:/var/www/html/wp-cli
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG='true'


  #########################################################################
  # WP-CLI
  #########################################################################
  
  wpcli:
  
    image: wordpress:cli
    container_name: fake-admin-wpcli
    depends_on:
      - db
      - wp
    volumes:
      - ./dev-env/wp:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/fake-admin
      - ./dev-env/wp-cli:/var/www/html/wp-cli
    command: sleep 3600
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG='true'


################ PIGEONPOSSE [FAKE ADMIN] - DOCKER-COMPOSE DEV ################