###############################################################################
# RELEASE
###############################################################################

name: Publish


###############################################################################
# ON
###############################################################################

on:
  push:
    tags:
      - '*'


###############################################################################
# JOBS
###############################################################################

jobs:

  build:

    name: Release in GitHub
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    ###########################################################################
    # STEPS
    ###########################################################################

    steps:

      #########################################################################
      # INIT & BUILD PKG
      #########################################################################
      - name: checks-out repository
        uses: actions/checkout@v3


      #########################################################################
      # IF IS IN MAIN BRANCH
      #########################################################################

      # - name: Exit if not on MAIN branch
      #   if: endsWith(github.ref, 'main') == false
      #   run: exit -1


      #########################################################################
      # BUILD PKG
      #########################################################################
      
      - name: Install composer
        uses: php-actions/composer@v6
        id: composer-install

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      - name: Install pkg dependencies
        run: |
          pnpm start
          pnpm build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      #########################################################################
      # GET PKG INFO
      #########################################################################

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1

      #########################################################################
      # GITHUB RELEASE
      #########################################################################

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/fake-admin.zip"
          body: |
            ℹ️ CHANGELOG: https://github.com/pigeonposse/fake-admin/blob/main/CHANGELOG.md
            📜 LICENSE: https://github.com/pigeonposse/fake-admin/blob/main/LICENSE


############################################################################### 