name: Publish release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Release in GitHub
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:

      #########################################################################
      # INIT
      #########################################################################

      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'pnpm'
      - name: ⬇️ Install php
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
      - name: ⬇️ Install composer
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"

      #########################################################################
      # BUILD PKG
      #########################################################################

      - name: Install pkg dependencies
        run: |
          export npm_config_build_from_source=false
          pnpm install --no-frozen-lockfile --ignore-scripts
          pnpm build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      #########################################################################
      # WORDPRESS PLUGIN DEPLOY
      #########################################################################

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          BUILD_DIR: plugin
          VERSION:  ${{ steps.package.outputs.version }}

      #########################################################################
      # GITHUB RELEASE
      #########################################################################

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/fake-admin.zip"
          body: |
            ℹ️ CHANGELOG: https://github.com/pigeonposse/fake-admin/blob/main/CHANGELOG.md
            📜 LICENSE: https://github.com/pigeonposse/fake-admin/blob/main/LICENSE


############################################################################### 